language: ruby
rvm:
- 2.1


install: 
    - gem install jekyll
    - jekyll build
    - ls


env:
  global:
  - FTP_USER=user # speeds up installation of html-proofer
  - FTP_PWD=password
  
 
 
after_success: find ./_site -type f -exec curl --ftp-create-dirs -u $FTP_USER:$FTP_PWD -T {} ftp://211.155.230.174/web/{} 