language: ruby
rvm:
- 2.1

install: gem install jekyll
script: jekyll build

after_script:
#  - cd ./public
  - ll


env:
  global:
  - FTP_USER=user # speeds up installation of html-proofer
  - FTP_PWD=password
  
  
deploy:
  script:  find ./make/output -type f -exec curl --ftp-create-dirs -u $FTP_USER:$FTP_PWD -T {} ftp://211.155.230.174/web/{} \\